### ISSUE TITLE
The issue of downloading Chrades-STA I3D features

### ISSUE THREAD

**Issue by Xun-Yang** [yytzsy/grounding_changing_distribution#2]
Hi,

It seems that the google drive link (https://drive.google.com/file/d/1P-kfWOQoHzSxd8vNpogNGyx8Jc4TKj4E/view?usp=sharing) for downloading the Charades-STA I3D features is expired.

Can you make it available for downloading again？

Thanks

**Comment by zjuchenlong** [comment]
Hi Xun,

    You can download the Charades-STA I3D features from the link in this repo: [https://github.com/yytzsy/SCDM](https://github.com/yytzsy/SCDM), and the download link is [https://cloud.tsinghua.edu.cn/f/b17bc7e9f17b4d0f8179/?dl=1](https://cloud.tsinghua.edu.cn/f/b17bc7e9f17b4d0f8179/?dl=1).

    We will update all the available download links in the repo soon.

> Hi,
> 
> It seems that the google drive link (https://drive.google.com/file/d/1P-kfWOQoHzSxd8vNpogNGyx8Jc4TKj4E/view?usp=sharing) for downloading the Charades-STA I3D features is expired.
> 
> Can you make it available for downloading again？
> 
> Thanks

·

**Comment by zjuchenlong** [comment]
You can download the Charades-STA I3D features from the link in this repo: [https://github.com/yytzsy/SCDM](https://github.com/yytzsy/SCDM), and the download link is [https://cloud.tsinghua.edu.cn/f/b17bc7e9f17b4d0f8179/?dl=1](https://cloud.tsinghua.edu.cn/f/b17bc7e9f17b4d0f8179/?dl=1).

We will update all the available download links in the repo soon.

**Comment by yytzsy** [comment]
Sorry for my late reply. I have updated the available download links in the repo.
